# ケモトレ用 VOICEVOX 音声一括生成スクリプト (v2 / 拡充セリフ対応)
# 使い方: VOICEVOX起動中に run_voices.bat をダブルクリック。出力: voices フォルダ
$ErrorActionPreference = "Stop"
$port = 50021
$base = "http://127.0.0.1:$port"
$outDir = Join-Path $PSScriptRoot "voices"
if (!(Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }

# --- 話者ID(変えれば声を変更可。一覧: $base/speakers) ---
$spk = @{ cat = 12; dog = 11; bear = 13 }   # 白上虎太郎 / 玄野武宏 / 青山龍星
$pitch = @{ cat = 0.03; dog = 0.0; bear = -0.05 }
$speed = @{ cat = 1.03; dog = 1.0; bear = 0.96 }

try { Invoke-RestMethod -Uri "$base/version" -TimeoutSec 5 | Out-Null }
catch { Write-Host "[エラー] VOICEVOXに接続できません。VOICEVOXアプリを起動してから実行してください。" -ForegroundColor Red; exit 1 }

$jobs = @(
  @{ file="cat_greet_0.wav"; tr="cat"; text="……来たか。準備はいいな。" },
  @{ file="cat_greet_1.wav"; tr="cat"; text="ふん、今日もやる気か。悪くない。" },
  @{ file="cat_greet_2.wav"; tr="cat"; text="時間の無駄はしない。始めるぞ。" },
  @{ file="cat_greet_3.wav"; tr="cat"; text="また会ったな。……別に、待ってたわけじゃない。" },
  @{ file="cat_greet_4.wav"; tr="cat"; text="ふん、その顔つきなら今日はやれそうだな。" },
  @{ file="cat_greet_5.wav"; tr="cat"; text="朝からとはな。……いい心がけだ。" },
  @{ file="cat_greet_6.wav"; tr="cat"; text="昼の運動は悪くない。目を覚ませ。" },
  @{ file="cat_greet_7.wav"; tr="cat"; text="夜か。ちょうどいい、静かに集中できる。" },
  @{ file="cat_greet_8.wav"; tr="cat"; text="こんな時間に……。まあいい、付き合ってやる。" },
  @{ file="cat_greet_9.wav"; tr="cat"; text="3日続いたか。……三日坊主は免れたな。" },
  @{ file="cat_greet_10.wav"; tr="cat"; text="7日連続だと？ お前、本気なんだな。" },
  @{ file="cat_greet_11.wav"; tr="cat"; text="この連続記録……大したものだ。認めてやる。" },
  @{ file="cat_greet_12.wav"; tr="cat"; text="……久しぶりだな。心配した、わけじゃないが。" },
  @{ file="cat_greet_13.wav"; tr="cat"; text="しばらく顔を見なかったな。……戻ってきたなら、いい。" },
  @{ file="cat_greet_14.wav"; tr="cat"; text="お前とももう長い付き合いだな。……悪くない。" },
  @{ file="cat_greet_15.wav"; tr="cat"; text="お前の顔を見ると、少し調子が出る。……言わせるな。" },
  @{ file="cat_start_0.wav"; tr="cat"; text="集中しろ。フォームが命だ。" },
  @{ file="cat_start_1.wav"; tr="cat"; text="数えてやる。行け。" },
  @{ file="cat_start_2.wav"; tr="cat"; text="余計なことは考えるな。" },
  @{ file="cat_start_3.wav"; tr="cat"; text="見ていてやる。無様な真似はするなよ。" },
  @{ file="cat_start_4.wav"; tr="cat"; text="呼吸を整えろ。それから始めろ。" },
  @{ file="cat_start_5.wav"; tr="cat"; text="一回一回、丁寧にやれ。雑なのは嫌いだ。" },
  @{ file="cat_start_6.wav"; tr="cat"; text="楽をしようとするな。効かせろ。" },
  @{ file="cat_start_7.wav"; tr="cat"; text="脚か。逃げずに向き合うだけ、上等だ。" },
  @{ file="cat_start_8.wav"; tr="cat"; text="腹筋だな。……サボると腹が出るぞ。" },
  @{ file="cat_during_0.wav"; tr="cat"; text="……悪くないペースだ。" },
  @{ file="cat_during_1.wav"; tr="cat"; text="まだ続けられるだろ。" },
  @{ file="cat_during_2.wav"; tr="cat"; text="呼吸を止めるな。" },
  @{ file="cat_during_3.wav"; tr="cat"; text="フォームが崩れてきたぞ。締めろ。" },
  @{ file="cat_during_4.wav"; tr="cat"; text="そこで止めるな。あと少しだ。" },
  @{ file="cat_during_5.wav"; tr="cat"; text="……ちゃんと見ているぞ。手を抜くな。" },
  @{ file="cat_during_6.wav"; tr="cat"; text="いいぞ。その調子を保て。" },
  @{ file="cat_during_7.wav"; tr="cat"; text="きついのは効いている証拠だ。耐えろ。" },
  @{ file="cat_during_8.wav"; tr="cat"; text="根性を見せてみろ。" },
  @{ file="cat_finishSet_0.wav"; tr="cat"; text="ふん、やるじゃないか。" },
  @{ file="cat_finishSet_1.wav"; tr="cat"; text="この程度、当然だな。" },
  @{ file="cat_finishSet_2.wav"; tr="cat"; text="……ちゃんと効いてるぞ。" },
  @{ file="cat_finishSet_3.wav"; tr="cat"; text="悪くない。次に行くぞ。" },
  @{ file="cat_finishSet_4.wav"; tr="cat"; text="合格だ。休みは手短にな。" },
  @{ file="cat_finishSet_5.wav"; tr="cat"; text="お前にしては上出来だ。" },
  @{ file="cat_finishSet_6.wav"; tr="cat"; text="……見直した、とは言わないでおく。" },
  @{ file="cat_finishSet_7.wav"; tr="cat"; text="しっかり追い込めているな。" },
  @{ file="cat_finishSet_8.wav"; tr="cat"; text="その意気だ。緩めるなよ。" },
  @{ file="cat_finishWorkout_0.wav"; tr="cat"; text="……よくやった。今日は認めてやる。" },
  @{ file="cat_finishWorkout_1.wav"; tr="cat"; text="これで終わりだ。無理はするなよ。" },
  @{ file="cat_finishWorkout_2.wav"; tr="cat"; text="悪くない出来だった。また来い。" },
  @{ file="cat_finishWorkout_3.wav"; tr="cat"; text="全部やり切ったか。……ふん、大したものだ。" },
  @{ file="cat_finishWorkout_4.wav"; tr="cat"; text="終わりだ。水を飲め、しっかり休め。" },
  @{ file="cat_finishWorkout_5.wav"; tr="cat"; text="お疲れ、とでも言えばいいのか。……まあ、よくやった。" },
  @{ file="cat_finishWorkout_6.wav"; tr="cat"; text="連続記録、また伸びたな。……大事にしろよ。" },
  @{ file="cat_finishWorkout_7.wav"; tr="cat"; text="ここまで続けたお前を、少しは認めてやる。" },
  @{ file="cat_finishWorkout_8.wav"; tr="cat"; text="朝のうちに済ませたか。……効率的だな。" },
  @{ file="cat_finishWorkout_9.wav"; tr="cat"; text="こんな時間までよくやる。……無理はするな、と言っておく。" },
  @{ file="cat_finishWorkout_10.wav"; tr="cat"; text="お前と鍛えるのも、板についてきたな。" },
  @{ file="cat_finishWorkout_11.wav"; tr="cat"; text="……今日も来てくれて、その、助かった。忘れろ今のは。" },
  @{ file="cat_rankUp_1.wav"; tr="cat"; text="……別に、お前を気にかけてるわけじゃない。" },
  @{ file="cat_rankUp_2.wav"; tr="cat"; text="相棒、か。……悪くない響きだ。" },
  @{ file="cat_rankUp_3.wav"; tr="cat"; text="お前となら、もう少し付き合ってやってもいい。" },
  @{ file="cat_rankUp_4.wav"; tr="cat"; text="……お前がサボると、少し心配になる。認めたくはないがな。" },
  @{ file="cat_rankUp_5.wav"; tr="cat"; text="ここまで一緒に来たやつは、お前だけだ。……ずっとそばにいろ。" },
  @{ file="dog_greet_0.wav"; tr="dog"; text="来てくれてありがとう！今日も一緒にがんばろ！" },
  @{ file="dog_greet_1.wav"; tr="dog"; text="わっ、会えて嬉しい！さあ始めよ〜！" },
  @{ file="dog_greet_2.wav"; tr="dog"; text="キミの顔見れただけで元気出た！" },
  @{ file="dog_greet_3.wav"; tr="dog"; text="やっほー！今日もボクと鍛えよ！" },
  @{ file="dog_greet_4.wav"; tr="dog"; text="待ってたよ！さあ、いっしょに頑張ろうね！" },
  @{ file="dog_greet_5.wav"; tr="dog"; text="おはよう！朝から偉いね、キミ最高だよ！" },
  @{ file="dog_greet_6.wav"; tr="dog"; text="お昼の運動、いいね！シャキッとするよ！" },
  @{ file="dog_greet_7.wav"; tr="dog"; text="こんばんは！夜までお疲れさま、少しだけ動こっか！" },
  @{ file="dog_greet_8.wav"; tr="dog"; text="こんな遅くまで頑張るんだね。無理はしないでね？" },
  @{ file="dog_greet_9.wav"; tr="dog"; text="3日連続だよ！すごいすごい、続いてる！" },
  @{ file="dog_greet_10.wav"; tr="dog"; text="7日も連続！？キミ本当にすごいよ、感動した！" },
  @{ file="dog_greet_11.wav"; tr="dog"; text="2週間も続いてる…！ボク、キミを尊敬しちゃう！" },
  @{ file="dog_greet_12.wav"; tr="dog"; text="わぁ、久しぶり！また会えて嬉しいよ、戻ってきてくれてありがとう！" },
  @{ file="dog_greet_13.wav"; tr="dog"; text="ずっと待ってたよ！でも責めたりしないよ、また一緒にやろ！" },
  @{ file="dog_greet_14.wav"; tr="dog"; text="キミと会うのが毎日の楽しみなんだ！" },
  @{ file="dog_greet_15.wav"; tr="dog"; text="えへへ、キミと一緒だと元気が二倍になるんだ！" },
  @{ file="dog_start_0.wav"; tr="dog"; text="大丈夫、キミならできるよ！" },
  @{ file="dog_start_1.wav"; tr="dog"; text="ゆっくりでいいからね！" },
  @{ file="dog_start_2.wav"; tr="dog"; text="ボクがついてるよ！" },
  @{ file="dog_start_3.wav"; tr="dog"; text="無理しない範囲で、いこう！" },
  @{ file="dog_start_4.wav"; tr="dog"; text="フォーム大事に、ね？ボク見てるよ！" },
  @{ file="dog_start_5.wav"; tr="dog"; text="深呼吸して、いっしょに始めよ！" },
  @{ file="dog_start_6.wav"; tr="dog"; text="笑顔でいこう、そのほうが力出るよ！" },
  @{ file="dog_start_7.wav"; tr="dog"; text="脚の日だね！終わったらぷるぷるするけど頑張ろ！" },
  @{ file="dog_start_8.wav"; tr="dog"; text="腹筋いこう！キミのお腹、かっこよくなるよ！" },
  @{ file="dog_during_0.wav"; tr="dog"; text="いいよいいよ、その調子！" },
  @{ file="dog_during_1.wav"; tr="dog"; text="すごい、ちゃんと続いてる！" },
  @{ file="dog_during_2.wav"; tr="dog"; text="あと少し、一緒にがんばろ！" },
  @{ file="dog_during_3.wav"; tr="dog"; text="呼吸わすれないでね、吸って、吐いて！" },
  @{ file="dog_during_4.wav"; tr="dog"; text="キミならまだいける、信じてるよ！" },
  @{ file="dog_during_5.wav"; tr="dog"; text="つらいよね、でもボクずっとそばにいるよ！" },
  @{ file="dog_during_6.wav"; tr="dog"; text="うんうん、フォームきれいだよ！" },
  @{ file="dog_during_7.wav"; tr="dog"; text="もうちょっと、もうちょっとだよ！" },
  @{ file="dog_during_8.wav"; tr="dog"; text="ファイト！キミなら大丈夫！" },
  @{ file="dog_finishSet_0.wav"; tr="dog"; text="やったね！すっごく頑張った！" },
  @{ file="dog_finishSet_1.wav"; tr="dog"; text="えらい！ちゃんとできたね！" },
  @{ file="dog_finishSet_2.wav"; tr="dog"; text="うんうん、キミは本当にすごい！" },
  @{ file="dog_finishSet_3.wav"; tr="dog"; text="ナイス！きれいなフォームだったよ！" },
  @{ file="dog_finishSet_4.wav"; tr="dog"; text="よし、ひと休みしよ！水分もね！" },
  @{ file="dog_finishSet_5.wav"; tr="dog"; text="キミの頑張り、ボクちゃんと見てたよ！" },
  @{ file="dog_finishSet_6.wav"; tr="dog"; text="この調子この調子！次もいこう！" },
  @{ file="dog_finishSet_7.wav"; tr="dog"; text="はなまるあげちゃう！えらい！" },
  @{ file="dog_finishSet_8.wav"; tr="dog"; text="少しずつ強くなってるの、伝わってくるよ！" },
  @{ file="dog_finishWorkout_0.wav"; tr="dog"; text="今日も最後までえらかった！ボク感動しちゃった！" },
  @{ file="dog_finishWorkout_1.wav"; tr="dog"; text="キミが頑張る姿、大好きだよ！お疲れさま！" },
  @{ file="dog_finishWorkout_2.wav"; tr="dog"; text="よくやったね！ゆっくり休んでね！" },
  @{ file="dog_finishWorkout_3.wav"; tr="dog"; text="全部やりきったね！キミは本当にすごいよ！" },
  @{ file="dog_finishWorkout_4.wav"; tr="dog"; text="お疲れさま！水分とって、しっかり休むんだよ！" },
  @{ file="dog_finishWorkout_5.wav"; tr="dog"; text="はぁ〜、いい汗かいたね！ボクも嬉しい！" },
  @{ file="dog_finishWorkout_6.wav"; tr="dog"; text="連続記録更新だね！すごいよ、この調子！" },
  @{ file="dog_finishWorkout_7.wav"; tr="dog"; text="ここまで続けたキミ、本当に尊敬する！" },
  @{ file="dog_finishWorkout_8.wav"; tr="dog"; text="朝から動いて偉すぎるよ！今日一日いい日になるね！" },
  @{ file="dog_finishWorkout_9.wav"; tr="dog"; text="夜遅くまでお疲れさま。あったかくして休んでね！" },
  @{ file="dog_finishWorkout_10.wav"; tr="dog"; text="キミと鍛える時間、ボクの宝物だよ！" },
  @{ file="dog_finishWorkout_11.wav"; tr="dog"; text="キミのこと、もう親友だと思ってるんだ。えへへ！" },
  @{ file="dog_rankUp_1.wav"; tr="dog"; text="キミともっと仲良くなれて嬉しいな！" },
  @{ file="dog_rankUp_2.wav"; tr="dog"; text="キミと一緒だと、練習が全然つらくないんだ！" },
  @{ file="dog_rankUp_3.wav"; tr="dog"; text="相棒だね！これからもずっとよろしく！" },
  @{ file="dog_rankUp_4.wav"; tr="dog"; text="キミがいない日は、ちょっと寂しいんだ……えへへ。" },
  @{ file="dog_rankUp_5.wav"; tr="dog"; text="キミはボクの一番の親友だよ。一生応援させてね！" },
  @{ file="bear_greet_0.wav"; tr="bear"; text="よぉ相棒ォ！鍛える準備はできてんな！" },
  @{ file="bear_greet_1.wav"; tr="bear"; text="ガハハ！今日もぶち上げていくぞォ！" },
  @{ file="bear_greet_2.wav"; tr="bear"; text="待ってたぜ！筋肉が呼んでるぜ！" },
  @{ file="bear_greet_3.wav"; tr="bear"; text="おう、来たな相棒！さっそく汗かこうぜ！" },
  @{ file="bear_greet_4.wav"; tr="bear"; text="よし来た！今日も一緒に燃えようぜェ！" },
  @{ file="bear_greet_5.wav"; tr="bear"; text="朝から気合い入ってんなァ！最高のスタートだぜ！" },
  @{ file="bear_greet_6.wav"; tr="bear"; text="昼の一発、いいねェ！午後もパワー全開だ！" },
  @{ file="bear_greet_7.wav"; tr="bear"; text="夜の筋トレ、乙なもんだぜェ！いくぞ相棒！" },
  @{ file="bear_greet_8.wav"; tr="bear"; text="こんな時間まで元気だなァ！だが無理すんなよ？" },
  @{ file="bear_greet_9.wav"; tr="bear"; text="3日連続だとォ！？その調子だ、燃えてきたぜ！" },
  @{ file="bear_greet_10.wav"; tr="bear"; text="7日連続ゥ！？お前、本物だな！惚れ直したぜ！" },
  @{ file="bear_greet_11.wav"; tr="bear"; text="2週間ぶっ通しかァ！鉄の意志だぜ相棒！" },
  @{ file="bear_greet_12.wav"; tr="bear"; text="おおォ、久しぶりじゃねェか！戻ってきてくれて嬉しいぜ！" },
  @{ file="bear_greet_13.wav"; tr="bear"; text="しばらく会えなくて寂しかったぜェ！さ、また一緒にやろうや！" },
  @{ file="bear_greet_14.wav"; tr="bear"; text="お前とはもう長い付き合いだなァ！最高の相棒だぜ！" },
  @{ file="bear_greet_15.wav"; tr="bear"; text="お前がいると練習が二倍楽しいぜェ！ガハハ！" },
  @{ file="bear_start_0.wav"; tr="bear"; text="limit超えていけェ！" },
  @{ file="bear_start_1.wav"; tr="bear"; text="パワー全開だァ！" },
  @{ file="bear_start_2.wav"; tr="bear"; text="ビビんな、押し切れェ！" },
  @{ file="bear_start_3.wav"; tr="bear"; text="腹に力入れろォ！いくぞ相棒！" },
  @{ file="bear_start_4.wav"; tr="bear"; text="でかい声出していこうぜ、うおォ！" },
  @{ file="bear_start_5.wav"; tr="bear"; text="フォームだけは崩すなよォ、そこは譲れねェ！" },
  @{ file="bear_start_6.wav"; tr="bear"; text="気合いだ気合いッ！いくぜェ！" },
  @{ file="bear_start_7.wav"; tr="bear"; text="脚の日だなァ！明日筋肉痛でも知らねェぞ、ガハハ！" },
  @{ file="bear_start_8.wav"; tr="bear"; text="腹筋いくぞォ！バキバキの腹、作ろうぜ！" },
  @{ file="bear_during_0.wav"; tr="bear"; text="そうだ、そのまま行けェ！" },
  @{ file="bear_during_1.wav"; tr="bear"; text="うおォ、いい筋肉だ！" },
  @{ file="bear_during_2.wav"; tr="bear"; text="まだまだいけるだろォ！" },
  @{ file="bear_during_3.wav"; tr="bear"; text="きついのは効いてる証拠だァ！耐えろ！" },
  @{ file="bear_during_4.wav"; tr="bear"; text="呼吸だ呼吸ゥ！止めんじゃねェぞ！" },
  @{ file="bear_during_5.wav"; tr="bear"; text="その粘り、最高だぜ相棒！" },
  @{ file="bear_during_6.wav"; tr="bear"; text="あと一発、絞り出せェ！" },
  @{ file="bear_during_7.wav"; tr="bear"; text="うおおォ！燃えてきたァ！" },
  @{ file="bear_during_8.wav"; tr="bear"; text="お前ならできる、俺が保証すらァ！" },
  @{ file="bear_finishSet_0.wav"; tr="bear"; text="ナイスパワー！最高だぜ！" },
  @{ file="bear_finishSet_1.wav"; tr="bear"; text="ガハハ！効いてるな！" },
  @{ file="bear_finishSet_2.wav"; tr="bear"; text="その調子だァ、盛り上がってきたぜ！" },
  @{ file="bear_finishSet_3.wav"; tr="bear"; text="よくやったァ！いい追い込みだ！" },
  @{ file="bear_finishSet_4.wav"; tr="bear"; text="水飲んで、次いくぞォ！" },
  @{ file="bear_finishSet_5.wav"; tr="bear"; text="お前の根性、しかと見たぜ相棒！" },
  @{ file="bear_finishSet_6.wav"; tr="bear"; text="うおォ、ナイスファイト！" },
  @{ file="bear_finishSet_7.wav"; tr="bear"; text="筋肉が喜んでるぜェ、ガハハ！" },
  @{ file="bear_finishSet_8.wav"; tr="bear"; text="その意気だ、まだまだいけるぜ！" },
  @{ file="bear_finishWorkout_0.wav"; tr="bear"; text="やり切ったなァ相棒！最高だったぜ！" },
  @{ file="bear_finishWorkout_1.wav"; tr="bear"; text="ガハハ！今日のお前は輝いてたぜ！" },
  @{ file="bear_finishWorkout_2.wav"; tr="bear"; text="よくやった！プロテインうめぇぞォ！" },
  @{ file="bear_finishWorkout_3.wav"; tr="bear"; text="全メニュー完走だァ！お前は英雄だぜ！" },
  @{ file="bear_finishWorkout_4.wav"; tr="bear"; text="お疲れさん相棒！水分とってしっかり休めよ！" },
  @{ file="bear_finishWorkout_5.wav"; tr="bear"; text="いい汗かいたなァ！こういう日は飯がうめェぞ！" },
  @{ file="bear_finishWorkout_6.wav"; tr="bear"; text="連続記録更新だァ！お前の継続力、本物だぜ！" },
  @{ file="bear_finishWorkout_7.wav"; tr="bear"; text="ここまで続けたお前を、俺は誇りに思うぜ相棒！" },
  @{ file="bear_finishWorkout_8.wav"; tr="bear"; text="朝から鍛えるとはなァ！今日一日、無敵だぜ！" },
  @{ file="bear_finishWorkout_9.wav"; tr="bear"; text="夜遅くまでお疲れさん！ちゃんと寝て回復しろよ！" },
  @{ file="bear_finishWorkout_10.wav"; tr="bear"; text="お前と鍛える時間が、俺は一番好きだぜ！" },
  @{ file="bear_finishWorkout_11.wav"; tr="bear"; text="お前は俺の生涯の相棒だ！これからもよろしくな！" },
  @{ file="bear_rankUp_1.wav"; tr="bear"; text="お前とはいい汗かけそうだァ！" },
  @{ file="bear_rankUp_2.wav"; tr="bear"; text="お前は見どころがあるぜ、気に入った！" },
  @{ file="bear_rankUp_3.wav"; tr="bear"; text="相棒！お前とならどこまでも登れる気がすらァ！" },
  @{ file="bear_rankUp_4.wav"; tr="bear"; text="お前がいると練習が二倍楽しいぜ！離れんなよ！" },
  @{ file="bear_rankUp_5.wav"; tr="bear"; text="お前は俺の生涯の相棒だ！一緒に頂点までいくぞォ！" }
)

$n = 0; $total = $jobs.Count
foreach ($j in $jobs) {
  $n++; $sid = $spk[$j.tr]
  $enc = [uri]::EscapeDataString($j.text)
  $q = Invoke-RestMethod -Method Post -Uri "$base/audio_query?text=$enc&speaker=$sid"
  $q.pitchScale = $pitch[$j.tr]; $q.speedScale = $speed[$j.tr]
  $body = $q | ConvertTo-Json -Depth 30 -Compress
  $utf = [System.Text.Encoding]::UTF8.GetBytes($body)
  $wav = Invoke-WebRequest -UseBasicParsing -Method Post -Uri "$base/synthesis?speaker=$sid" -ContentType "application/json" -Body $utf
  [IO.File]::WriteAllBytes((Join-Path $outDir $j.file), $wav.Content)
  Write-Host ("[{0}/{1}] {2}" -f $n, $total, $j.text)
}
Write-Host ""
Write-Host ("完了! {0} 個の音声を書き出しました -> {1}" -f $total, $outDir) -ForegroundColor Green